feat(web): joke app created
lydia321/Web pull request #1
Opened 2024-02-09 21:19 UTC by lydia321

Welcome to Jokes Central! This React application provides users with a platform to enjoy a collection of random jokes. With a sleek and user-friendly interface, users can easily search for jokes, filter them by category, and enjoy a good laugh.

Features: Joke Display: View a random assortment of jokes fetched from an external API. Search Functionality: Search for jokes based on keywords to find specific jokes of interest. Category Filtering: Filter jokes by category to narrow down the type of jokes displayed. Dynamic Updates: Real-time updates ensure a seamless user experience, with loading indicators during data retrieval. Responsive Design: The application is designed to be responsive, ensuring compatibility across various devices and screen sizes.

How to Use: Accessing the Application: Visit the deployed application link or clone the repository to run it locally. Viewing Jokes: Upon accessing the application, users are greeted with a collection of random jokes displayed on the homepage. Searching for Jokes: Use the search bar provided to enter keywords and search for specific jokes. Filtering by Category: Click on category buttons to filter jokes based on specific categories. Enjoying Jokes: Sit back, relax, and enjoy a good laugh with the assortment of jokes available on Jokes Central!

Technologies Used: React: Frontend development framework for building user interfaces. Next.js: React framework for server-side rendering and static site generation. Tailwind CSS: Utility-first CSS framework for styling the application. TypeScript: Superset of JavaScript with static typing for enhanced development experience. API Integration: Utilizes external APIs to fetch jokes and provide dynamic content.

Image Illustration: (https://github.com/lydia321/Assesment/assets/42097132/7755252a-361d-46c3-9110-0d7b67a89e3c)

2024-02-12 09:17 UTC, LibenHailu commented on joke-app/src/app/api/jokes-api.ts
api folder has  a special meaning It is better if we extract our API slice to different folder like services or features outside app directory,  since having route.ts file in this directory may lead to hard to debug bugs.
https://nextjs.org/docs/app/building-your-application/routing/route-handlers

2024-02-12 09:18 UTC, LibenHailu commented on joke-app/src/app/api/jokes-api.ts
> +        method: "GET",
In query it is not necessary to add method, but you can keep it as it is as well.

2024-02-12 09:20 UTC, LibenHailu commented on joke-app/src/app/api/jokes-api.ts
> +    getAllJokes: builder.query<{jokes: Joke[]}, any>({
We can add the proper type or remove it, form here 
my suggestion is to write it like 

getAllJokes: builder.query({
   query:  ()=>"/my-jokes"
})

2024-02-12 09:23 UTC, LibenHailu commented on joke-app/src/app/layout.tsx
It is better to extract your providers to another component and keeping this a server component. 
so that you can export meta tags easily 

export const metadata: Metadata = {
 title: "my-jokes"
}

2024-02-12 09:26 UTC, LibenHailu commented on joke-app/src/app/types/Joke.ts
It is better to keep this named export in order to avoid this 

import RandomType from "./types/Joke.ts"

It is just typescript file Why is it not names jok.ts

2024-02-12 09:27 UTC, LibenHailu commented on joke-app/src/app/types/Joke.ts
Lets move this out of the app directory since having page file may lead to hard to debug bugs.

2024-02-12 09:29 UTC, LibenHailu commented on joke-app/src/components/JokesDisplay.tsx
You can extract isLoading from useGetAllJokesQuery hook, and lets not filter locally use the API to fetch jokes based on selected categories.

2024-02-12 09:30 UTC, LibenHailu commented on joke-app/src/components/JokesDisplay.tsx
In case of the error there is no component in charge of handling the error or showing error status.

https://nextjs.org/docs/app/building-your-application/routing/error-handling

2024-02-12 09:33 UTC, LibenHailu commented on joke-app/src/store.ts
I personally like it when api slices are named like jokeApiSlice or jokeApi since they are not conventional type of slices.

2024-02-12 09:33 UTC, LibenHailu commented on joke-app/src/store.ts
This is my personal option you dont have to act on it

2024-02-12 09:35 UTC, LibenHailu requested changes
Lets Update the  UI to make it more appealing.

2024-02-12 18:18 UTC, lydia321 commented on joke-app/src/app/layout.tsx
Can you elaborate on this? how can i add the meta data on the root?

2024-02-12 18:28 UTC, lydia321 commented on joke-app/src/app/types/Joke.ts
i understand joke.ts should be start with a small letter because its not a component, is that what you meant? im not clear on the rest of this comment?

2024-02-12 18:37 UTC, lydia321 commented on joke-app/src/components/JokesDisplay.tsx
Noted. good point

2024-02-13 18:26 UTC, LibenHailu approved these changes
LGTM

2024-02-13 18:46 UTC, merged